### ISSUE TITLE
When enter number after spaces, it is working good) But, we can make it's looking better with removing these spaces ))

### ISSUE THREAD

**Issue by Ndn1618** [ilhomjon55/fizzBuzzAdvanced#1]
![Screenshot_6](https://user-images.githubusercontent.com/68459485/98549866-33e8f300-22bd-11eb-95c5-37b35c810ee1.png)

**Comment by ilhomjon55** [comment]
done, thank you

**Comment by Ndn1618** [comment]
Now works perfectly! 👍
